# Generated by Django 2.0 on 2019-09-19 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='deliveryoption',
            field=models.CharField(default='7Am', max_length=100),
            preserve_default=False,
        ),
    ]
