# Generated by Django 2.0 on 2019-09-19 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_orderitem_deliveryoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='total',
            field=models.CharField(default='Rs. 0', max_length=20),
            preserve_default=False,
        ),
    ]
