# Generated by Django 2.1.5 on 2019-09-21 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_orderitem_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='ordered_date',
            field=models.DateField(default='2019-09-12'),
            preserve_default=False,
        ),
    ]
