# Generated by Django 2.1.5 on 2019-09-21 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_orderitem_ordered_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='ordered_date',
            field=models.DateField(default='2019-09-19'),
            preserve_default=False,
        ),
    ]
