# Generated by Django 2.1.5 on 2019-09-21 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_orderitem_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='start_date',
        ),
    ]
