# Generated by Django 2.1.5 on 2019-09-21 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_orderitem_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='ordered_date',
            field=models.DateField(default='2019-09-21'),
        ),
    ]
