# Generated by Django 2.1.5 on 2019-09-21 09:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20190921_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='ordered_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
