# Generated by Django 2.1.5 on 2019-09-21 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_order_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
