# Generated by Django 2.1.5 on 2019-11-18 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_order_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
    ]
